# Generated by Django 3.0.4 on 2020-04-11 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_auto_20200401_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_stocks',
            name='port_id',
            field=models.ForeignKey(db_column='port_id', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_stocks', to='portfolio.Portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio_stocks',
            name='stock_id',
            field=models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_stocks', to='portfolio.Stocks'),
        ),
        migrations.AlterField(
            model_name='user_portfolio',
            name='portfolio_id',
            field=models.ForeignKey(db_column='portfolio_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolio', to='portfolio.Portfolio'),
        ),
        migrations.AlterField(
            model_name='user_portfolio',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='portfolio',
            table='portfolio',
        ),
        migrations.AlterModelTable(
            name='portfolio_stocks',
            table='portfolio_stock',
        ),
        migrations.AlterModelTable(
            name='stocks',
            table='stocks',
        ),
        migrations.AlterModelTable(
            name='user_portfolio',
            table='user_portfolio',
        ),
    ]
