# Generated by Django 3.0.4 on 2020-04-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200401_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='forecast_return',
            field=models.FloatField(default=0),
        ),
    ]
