# Generated by Django 3.0.3 on 2020-04-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200411_1333'),
        ('portfolio', '0003_stocks_forecast_return'),
    ]

    operations = [
    ]
