# Generated by Django 3.0.4 on 2020-04-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_merge_20200415_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='mse',
            field=models.FloatField(default=0),
        ),
    ]
