# Generated by Django 3.0.4 on 2020-04-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_stocks_mse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='created_at',
        ),
    ]
