# Generated by Django 3.0.4 on 2020-04-15 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200415_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_stocks',
            name='port_id',
            field=models.ForeignKey(db_column='port_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='portfolio_stocks', to='portfolio.Portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio_stocks',
            name='stock_id',
            field=models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='portfolio_stocks', to='portfolio.Stocks'),
        ),
    ]
