# Generated by Django 3.0.3 on 2020-04-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200415_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cagr',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='max_drawdown',
        ),
    ]
